/* eslint-disable*/
export const ADD_ARTICLES = "ADD_ARTICLES";
export const EMPTY_ARTICLES = "EMPTY_ARTICLES";

export const ADD_TOPICS = "ADD_TOPICS";

export const START_LOADING_TOPICS = "START_LOADING_TOPICS";
export const STOP_LOADING_TOPICS = "STOP_LOADING_TOPICS";

export const SET_CURRENT_ARTICLE = "SET_CURRENT_ARTICLE";
export const EMPTY_CURRENT_ARTICLE = "EMPTY_CURRENT_ARTICLE";

export const START_LOADING_ARTICLES = "START_LOADING_ARTICLES";
export const STOP_LOADING_ARTICLES = "STOP_LOADING_ARTICLES";
