export const START_LOADING_APP = "START_LOADING_APP";
export const STOP_LOADING_APP = "STOP_LOADING_APP";

export const ADD_ARTICLES = "ADD_ARTICLES";
export const EMPTY_ARTICLES = "EMPTY_ARTICLES";

export const ADD_TOPICS = "ADD_TOPICS";
export const EMPTY_TOPICS = "EMPTY_TOPICS";

export const START_LOADING_TOPICS = "START_LOADING_TOPICS";
export const STOP_LOADING_TOPICS = "STOP_LOADING_TOPICS";

export const SET_CURRENT_TOPIC = "SET_CURRENT_TOPIC";
export const EMPTY_CURRENT_TOPIC = "EMPTY_CURRENT_TOPIC";

export const SET_CURRENT_ARTICLE = "SET_CURRENT_ARTICLE";
export const EMPTY_CURRENT_ARTICLE = "EMPTY_CURRENT_ARTICLE";

export const START_LOADING_ARTICLES = "START_LOADING_ARTICLES";
export const STOP_LOADING_ARTICLES = "STOP_LOADING_ARTICLES";

export const ADD_USERS = "ADD_USERS";
export const EMPTY_USERS = "EMPTY_USERS";

export const START_LOADING_USERS = "START_LOADING_USERS";
export const STOP_LOADING_USERS = "STOP_LOADING_USERS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const EMPTY_CURRENT_USER = "EMPTY_CURRENT_USER";

export const ADD_ARCHIVES = "ADD_ARCHIVES";
export const EMPTY_ARCHIVES = "EMPTY_ARCHIVES";

export const START_LOADING_ARCHIVES = "START_LOADING_ARCHIVES";
export const STOP_LOADING_ARCHIVES = "STOP_LOADING_ARCHIVES";

export const SET_CURRENT_ARCHIVE = "SET_CURRENT_ARCHIVE";
export const EMPTY_CURRENT_ARCHIVE = "EMPTY_CURRENT_ARCHIVE";

// Action types that probably won't have any reducers
// I'll be using them to group actions to handle them in our saga

export const LOAD_HOMEPAGE = "LOAD_HOMEPAGE";
export const DISPOSE_HOMEPAGE = "DISPOSE_HOMEPAGE";

export const FETCH_ARTICLES_BY_TOPIC = "FETCH_ARTICLES_BY_TOPIC";
export const LOAD_ARTICLE_PAGE = "LOAD_ARTICLE_PAGE";
export const DISPOSE_ARTICLE_PAGE = "DISPOSE_ARTICLE_PAGE";

export const LOAD_ARCHIVES_PAGE = "LOAD_ARCHIVES_PAGE";
export const DISPOSE_ARCHIVES_PAGE = "DISPOSE_ARCHIVES_PAGE";

export const FETCH_ARCHIVE_BY_ID = "FETCH_ARCHIVE_BY_ID";

export const LOAD_USERS_PAGE = "LOAD_USERS_PAGE";
export const DISPOSE_USERS_PAGE = "DISPOSE_USERS_PAGE";

export const LOAD_EDIT_USER = "LOAD_EDIT_USER";
export const DISPOSE_EDIT_USER = "DISPOSE_EDIT_USER";

export const LOAD_TOPICS_PAGE = "LOAD_TOPICS_PAGE";
export const DISPOSE_TOPICS_PAGE = "DISPOSE_TOPICS_PAGE";

export const LOAD_EDIT_TOPIC = "LOAD_EDIT_TOPIC";
export const DISPOSE_EDIT_TOPIC = "DISPOSE_EDIT_TOPIC";

export const SET_ARTICLE_SEARCH_QUERY = "SET_ARTICLE_SEARCH_QUERY";
export const EMPTY_ARTICLE_SEARCH_QUERY = "EMPTY_ARTICLE_SEARCH_QUERY";

export const ADD_ARTICLE_SEARCH_RESULTS = "ADD_ARTICLE_SEARCH_RESULTS";
export const EMPTY_ARTICLE_SEARCH_RESULTS = "EMPTY_ARTICLE_SEARCH_RESULTS";

export const START_LOADING_ARTICLE_SEARCH_RESULTS = "START_LOADING_ARTICLE_SEARCH_RESULTS";
export const STOP_LOADING_ARTICLE_SEARCH_RESULTS = "STOP_LOADING_ARTICLE_SEARCH_RESULTS";

export const LOAD_ARTICLE_SEARCH_PAGE = "LOAD_ARTICLE_SEARCH_PAGE";
export const DISPOSE_ARTICLE_SEARCH_PAGE = "DISPOSE_ARTICLE_SEARCH_PAGE";
